#! /bin/sh -f

# Darwin
#   Gtk+, OpenGL and GLX
#     using Gtk+ as GUI library
#       Gtk+ should be Ver. 2.*
#     using OpenGL as graphics library
#     using GLX as glue between Gtk+ and OpenGL

opengl_libs="-L/usr/X11R6/lib -lGLU -lGL"
gtk_libs=`pkg-config --libs gtk+-2.0`

libs="${opengl_libs} ${gtk_libs} -lX11"

echo "${libs} "
