#! /bin/sh -f

# Linux
#   Gtk+, OpenGL and GLX (on Linux)
#     using Gtk+ as GUI library
#       Gtk+ should be Ver. 2.*
#     using OpenGL as graphics library
#     using GLX as glue between Gtk+ and OpenGL

opengl_libs="-lGLU -lGL"
gtk_libs=`pkg-config --libs gtk+-2.0`

libs="${opengl_libs} ${gtk_libs} -dylib_file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib -lX11"

echo "${libs} "
